step1 :all modified wcslib files from version 4.7 to 4.13.4

diff --git a/borrow/wcslib/C/GNUmakefile b/borrow/wcslib/C/GNUmakefile
--- a/borrow/wcslib/C/GNUmakefile
+++ b/borrow/wcslib/C/GNUmakefile
@@ -1,5 +1,5 @@
 #-----------------------------------------------------------------------------
-# GNU makefile for building WCSLIB 4.7 and its test suite.
+# GNU makefile for building WCSLIB 4.13 and its test suite.
 #
 # Summary of the main targets
 # ---------------------------
@@ -13,11 +13,15 @@
 #              library the C source files generated by 'flex'.
 #
 #   check (or test): Compile and run the test programs.  By default they are
-#              executed in batch mode; use
+#              executed in batch mode, and non-graphical tests only report
+#              "PASS" on success.  Use
 #
-#                gmake MODE=interactive check
+#                make MODE=interactive check
 #
-#              to run them interactively.
+#              to run them interactively with full diagnostic output.  To skip
+#              graphical tests even if PGPLOT is available, use
+#
+#                make CHECK=nopgplot check
 #
 #   tests:     Compile the test programs (but don't run them).
 #
@@ -63,29 +67,42 @@ ifneq "$(DO_WCSHDR)" ""
   CPPFLAGS += -DDO_WCSHDR
 endif
 
-# Test programs that don't require PGPLOT.
-TEST_N := tlin tlog tprj1 tsph tspx ttab1 twcs twcssub tpih1 tbth1 tfitshdr \
-          tunits twcsfix
+# Test programs that don't require CFITSIO or PGPLOT.
+TEST_N := tlin tlog tprj1 tsph tsphdpa tspx ttab1 twcs twcssub tpih1 tbth1 \
+          tfitshdr tunits twcsfix
 
-# Test programs that do require PGPLOT.
+# Test programs that require CFITSIO (they don't need PGPLOT).
+TEST_C := twcstab twcshdr
+
+# Test programs that require PGPLOT but not PGSBOX.
 TEST_P := tspc tprj2 tcel1 tcel2 ttab2 ttab3 twcsmix
 
+# Test programs that require PGPLOT and PGSBOX.
+TEST_B := tpih2
+
 # Test programs that aren't automatically exercised.
-TEST_X := tsphdpa
+TEST_X := tsphdpa twcshdr
 
 TESTS  := $(TEST_N)
-ifneq "$(PGPLOTINC)" ""
-ifneq "$(PGPLOTLIB)" ""
-  TESTS   += $(TEST_P) tpih2
+
+# Add test programs that require CFITSIO if we have it.
+ifneq "$(CFITSIOINC)" ""
+ifneq "$(CFITSIOLIB)" ""
+  TESTS += $(TEST_C)
 endif
 endif
 
-# Test programs that require CFITSIO.
-ifneq "$(CFITSIOINC)" ""
-ifneq "$(CFITSIOLIB)" ""
-  TESTS  += twcstab twcshdr
+# Add test programs that require PGPLOT if we have it.
+ifneq "$(CHECK)" "nopgplot"
+ifneq "$(PGPLOTINC)" ""
+ifneq "$(PGPLOTLIB)" ""
+  TESTS += $(TEST_P) $(TEST_B)
 endif
 endif
+endif
+
+# Remove tests that aren't automatically exercised.
+TESTS := $(filter-out $(TEST_X), $(TESTS))
 
 PGSBOXLIB := ../pgsbox/libpgsbox-$(LIBVER).a
 
@@ -121,6 +138,7 @@ $(PICLIB)(%.o) : %.c
 	-@ $(RM) $@
 	   $(CPP) $(CPPFLAGS) $(CFLAGS) $< > $@
 
+# Print out include file dependencies.
 %.d : %.c
 	-@ echo ''
 	-@ $(CPP) $(CPPFLAGS) $(CFLAGS) $< | \
@@ -131,21 +149,69 @@ $(PICLIB)(%.o) : %.c
 run_% : %
 	-@ echo ''
 	-@ $(TIMER)
-	 @ if [ '$(MODE)' = interactive ] ; then \
+	 @ if [ '$(MODE)' = interactive -o '$(VALGRIND)' ] ; then \
 	     printf 'Press <CR> to run $<: ' ; \
 	     read DUMMY ; \
+	   fi ; \
+	   if [ '$(VALGRIND)' ] ; then \
 	     if [ '$<' = tunits ] ; then \
 	       $(VALGRIND) ./$< < test/units_test ; \
-	     elif [ '$<' != twcshdr ] ; then \
+	     else \
 	       $(VALGRIND) ./$< ; \
 	     fi ; \
 	   else \
-	     if [ '$<' = tcel2 ] ; then \
-	       echo N | $(VALGRIND) ./$< ; \
-	     elif [ '$<' = tunits ] ; then \
-	       $(VALGRIND) ./$< < test/units_test ; \
-	     elif [ '$<' != twcshdr ] ; then \
-	       $(VALGRIND) ./$< < /dev/null 2>&1 ; \
+	     if [ '$(filter $<, $(TEST_N) $(TEST_C))' ] ; then \
+	       if [ '$<' = tunits ] ; then \
+	         if [ '$(MODE)' = interactive ] ; then \
+	           ./$< < test/units_test 2>&1 | tee $<.out ; \
+	         else \
+	           ./$< < test/units_test > $<.out 2>&1 ; \
+	         fi ; \
+	       else \
+	         if [ '$(MODE)' = interactive ] ; then \
+	           ./$< < /dev/null 2>&1 | tee $<.out ; \
+	         else \
+	           ./$< < /dev/null > $<.out 2>&1 ; \
+	         fi ; \
+	       fi ; \
+	       if grep 'PASS:' $<.out > /dev/null ; then \
+	         if [ '$(MODE)' != interactive ] ; then \
+	           head -2 $<.out ; \
+	           grep 'PASS:' $<.out ; \
+	         fi ; \
+	         echo 'PASS: C/$<' >> test_results ; \
+	       elif [ -f 'test/$<.out' ] ; then \
+	         trap 'rm -f run_test.tmp' 0 1 2 3 15 ; \
+	         sed -e 's/0x[0-9a-f][0-9a-f][0-9a-f]*/0x<address>/g' $<.out > \
+	           run_test.tmp ; \
+	         mv -f run_test.tmp $<.out ; \
+	         if cmp -s $<.out test/$<.out ; then \
+	           if [ '$(MODE)' != interactive ] ; then \
+	             head -1 $<.out ; \
+	           fi ; \
+	           echo '' ; \
+	           echo 'PASS: Output agrees with C/test/$<.out' ; \
+	           echo 'PASS: C/$<' >> test_results ; \
+	         else \
+	           if [ '$(MODE)' != interactive ] ; then \
+	             cat $<.out ; \
+	           fi ; \
+	           echo '' ; \
+	           echo 'FAIL: Output disagrees with C/test/$<.out' ; \
+	           echo 'FAIL: C/$<' >> test_results ; \
+	         fi ; \
+	       elif [ '$(MODE)' != interactive ] ; then \
+	         cat $<.out ; \
+	         echo 'FAIL: C/$<' >> test_results ; \
+	       fi ; \
+	     elif [ '$(MODE)' = interactive ] ; then \
+	       ./$< ; \
+	     else \
+	       if [ '$<' = tcel2 ] ; then \
+	         echo N | ./$< ; \
+	       else \
+	         ./$< < /dev/null 2>&1 ; \
+	       fi ; \
 	     fi ; \
 	   fi
 	-@ echo ''
@@ -171,7 +237,7 @@ $(SHRLIB) : $(PICLIB)
 	     cd tmp && \
 	     trap 'cd .. ; $(RM) -r tmp' 0 1 2 3 15 ; \
 	     $(AR) x ../$(PICLIB) && \
-	     $(SHRLD) $(LDFLAGS) -o $@ *.o && \
+	     $(SHRLD) -o $@ *.o $(LDFLAGS) $(LIBS) && \
 	     mv $@ ..
 
 $(PICLIB) : $(MODULES:%.o=$(PICLIB)(%.o)) ;
@@ -188,11 +254,15 @@ install : build
 	-  $(LN_S) $(WCSLIB) $(LIBDIR)/libwcs.a
 	-  if [ "$(SHRLIB)" != "" ] ; then \
 	     $(INSTALL) -m 644 $(SHRLIB) $(LIBDIR) ; \
+	     if [ -h "$(LIBDIR)/$(SONAME)" ] ; then \
+	       $(RM) $(LIBDIR)/$(SONAME) ; \
+	     fi ; \
+	     $(LN_S) $(SHRLIB) $(LIBDIR)/$(SONAME) ; \
 	     if [ "$(SHRLN)" != "" ] ; then \
 	       if [ -h "$(LIBDIR)/$(SHRLN)" ] ; then \
 	         $(RM) $(LIBDIR)/$(SHRLN) ; \
 	       fi ; \
-	       $(LN_S) $(SHRLIB) $(LIBDIR)/$(SHRLN) ; \
+	       $(LN_S) $(SONAME) $(LIBDIR)/$(SHRLN) ; \
 	     fi ; \
 	   fi
 	-  if [ ! -d "$(INCDIR)" ] ; then \
@@ -203,13 +273,14 @@ install : build
 	   $(LN_S) $(notdir $(INCDIR)) $(INCLINK)
 
 clean :
-	- $(RM) -r *.o *.i a.out core *.dSYM $(EXTRA_CLEAN)
+	- $(RM) -r *.o *.i a.out t*.out core *.dSYM $(EXTRA_CLEAN)
 
 cleaner : clean
+	-  $(RM) .gdb_history
 	-  $(RM) $(TEST_N) $(TEST_X)
 	-  $(RM) $(TEST_P) tpih2 twcstab twcshdr
 	-  $(RM) tofits bth.fits pih.fits wcstab.fits
-	-  $(RM) t*_cfitsio
+	-  $(RM) t*_cfitsio test_results
 
 cleanest distclean realclean : cleaner
 	-  $(RM) ../wcsconfig.h ../wcsconfig_tests.h
@@ -218,50 +289,50 @@ cleanest distclean realclean : cleaner
 
 check test : tests $(TESTS:%=run_%)
 
-tests : $(TESTS)
+tests : $(TESTS) $(TEST_X)
 
-$(TEST_N) $(TEST_X) : % : test/%.c $(WCSLIB)
+$(TEST_N) : % : test/%.c $(WCSLIB)
 	-@ echo ''
-	   $(CC) $(CPPFLAGS) $(CFLAGS) $(LDFLAGS) -o $@ $< $(WCSLIB) $(LIBS)
+	   $(CC) $(CPPFLAGS) $(CFLAGS) -o $@ $< $(LDFLAGS) $(WCSLIB) $(LIBS)
 	-@ $(RM) $@.o
 
 $(TEST_P) : % : test/%.c $(WCSLIB)
 	-@ echo ''
 	   $(CC) $(CPPFLAGS) $(PGPLOTINC) $(CFLAGS) -c -o $@.o $<
-	   $(LD) $(LDFLAGS) -o $@ $@.o $(PGPLOTLIB) $(WCSLIB) $(LIBS)
+	   $(LD) -o $@ $@.o $(LDFLAGS) $(PGPLOTLIB) $(WCSLIB) $(FLIBS) $(LIBS)
 	-@ $(RM) $@.o
 
 tpih2 : test/tpih2.c $(PGSBOXLIB) $(WCSLIB)
 	-@ echo ''
 	   $(CC) $(CPPFLAGS) -I../pgsbox $(PGPLOTINC) $(CFLAGS) -c -o $@.o $<
-	   $(LD) $(LDFLAGS) -o $@ $@.o $(PGSBOXLIB) $(PGPLOTLIB) $(WCSLIB) \
+	   $(LD) -o $@ $@.o $(LDFLAGS) $(PGSBOXLIB) $(PGPLOTLIB) $(WCSLIB) \
 	     $(FLIBS) $(LIBS)
 	-@ $(RM) $@.o
 
 tfitshdr_cfitsio tpih1_cfitsio tbth1_cfitsio : %_cfitsio : test/%.c $(WCSLIB)
 	-@ echo ''
 	   $(CC) -DDO_CFITSIO $(CPPFLAGS) $(CFITSIOINC) $(CFLAGS) \
-	     $(LDFLAGS) -o $@ $< $(CFITSIOLIB) $(WCSLIB) $(LIBS)
+	     -o $@ $< $(LDFLAGS) $(CFITSIOLIB) $(WCSLIB) $(LIBS)
 	-@ $(RM) $@.o
 
 tpih2_cfitsio : test/tpih2.c $(PGSBOXLIB) $(WCSLIB)
 	-@ echo ''
 	   $(CC) -DDO_CFITSIO $(CPPFLAGS) -I../pgsbox $(PGPLOTINC) \
 	     $(CFITSIOINC) $(CFLAGS) -c -o $@.o $<
-	   $(LD) $(LDFLAGS) -o $@ $@.o $(PGSBOXLIB) $(PGPLOTLIB) \
+	   $(LD) -o $@ $@.o $(LDFLAGS) $(PGSBOXLIB) $(PGPLOTLIB) \
 	     $(CFITSIOLIB) $(WCSLIB) $(FLIBS) $(LIBS)
 	-@ $(RM) $@.o
 
 twcstab : test/twcstab.c $(GETWCSTAB) $(WCSLIB)
 	-@ echo ''
-	   $(CC) $(CPPFLAGS) $(CFITSIOINC) $(CFLAGS) $(LDFLAGS) -o $@ $< \
-	     $(GETWCSTAB) $(CFITSIOLIB) $(WCSLIB) $(LIBS)
+	   $(CC) $(CPPFLAGS) $(CFITSIOINC) $(CFLAGS) -o $@ $< $(GETWCSTAB) \
+	     $(LDFLAGS) $(CFITSIOLIB) $(WCSLIB) $(LIBS)
 	-@ $(RM) $@.o
 
 twcshdr : test/twcshdr.c $(GETWCSTAB) $(WCSLIB)
 	-@ echo ''
-	   $(CC) $(CPPFLAGS) $(CFITSIOINC) $(CFLAGS) $(LDFLAGS) -o $@ $< \
-	     $(GETWCSTAB) $(CFITSIOLIB) $(WCSLIB) $(LIBS)
+	   $(CC) $(CPPFLAGS) $(CFITSIOINC) $(CFLAGS) -o $@ $< $(GETWCSTAB) \
+	     $(LDFLAGS) $(CFITSIOLIB) $(WCSLIB) $(LIBS)
 	-@ $(RM) $@.o
 
 getwcstab.o : getwcstab.c getwcstab.h
@@ -292,63 +363,74 @@ show ::
 	-@ -@ echo '  FLEXMODS    := $(FLEXMODS)'
 	-@ -@ echo '  MODULES     := $(MODULES)'
 
-# Dependencies
-#-------------
+# Dependencies (use the %.d pattern rule to list them)
+#-----------------------------------------------------
 
-$(WCSLIB)(cel.o)      : cel.h prj.h sph.h wcsmath.h wcsprintf.h wcstrig.h
+$(WCSLIB)(cel.o)      : cel.h prj.h sph.h wcsconfig.h wcserr.h wcsmath.h \
+                        wcsprintf.h wcstrig.h
 $(WCSLIB)(fitshdr.o)  : wcsconfig.h fitshdr.h
-$(WCSLIB)(lin.o)      : lin.h wcsprintf.h
+$(WCSLIB)(lin.o)      : lin.h wcserr.h wcsprintf.h
 $(WCSLIB)(log.o)      : log.h
-$(WCSLIB)(prj.o)      : prj.h wcsmath.h wcsprintf.h wcstrig.h
-$(WCSLIB)(spc.o)      : spc.h spx.h wcsmath.h wcsprintf.h wcstrig.h
-$(WCSLIB)(sph.o)      : sph.h wcstrig.h
-$(WCSLIB)(spx.o)      : spx.h
-$(WCSLIB)(tab.o)      : tab.h wcsmath.h wcsprintf.h
+$(WCSLIB)(prj.o)      : prj.h wcsconfig.h wcserr.h wcsmath.h wcsprintf.h \
+                        wcstrig.h wcsutil.h
+$(WCSLIB)(spc.o)      : spc.h spx.h wcserr.h wcsmath.h wcsprintf.h wcstrig.h \
+                        wcsutil.h
+$(WCSLIB)(sph.o)      : sph.h wcsconfig.h wcstrig.h
+$(WCSLIB)(spx.o)      : spx.h wcserr.h wcsmath.h
+$(WCSLIB)(tab.o)      : tab.h wcserr.h wcsmath.h wcsprintf.h
 $(WCSLIB)(wcs.o)      : cel.h lin.h log.h prj.h spc.h sph.h spx.h tab.h \
-                        wcs.h wcsmath.h wcstrig.h wcsprintf.h wcsunits.h \
-                        wcsutil.h
-$(WCSLIB)(wcsbth.o)   : cel.h lin.h prj.h spc.h spx.h tab.h wcs.h wcshdr.h \
-                        wcsmath.h
+                        wcs.h wcsconfig.h wcserr.h wcsmath.h wcsprintf.h \
+                        wcstrig.h wcsunits.h wcsutil.h
+$(WCSLIB)(wcsbth.o)   : cel.h lin.h prj.h spc.h spx.h tab.h wcs.h wcserr.h \
+                        wcshdr.h wcsmath.h
+$(WCSLIB)(wcserr.o)   : wcserr.h wcsprintf.h
 $(WCSLIB)(wcsfix.o)   : cel.h lin.h prj.h spc.h sph.h spx.h tab.h wcs.h \
-                        wcsfix.h wcsmath.h wcsunits.h
-$(WCSLIB)(wcshdr.o)   : cel.h lin.h prj.h spc.h spx.h tab.h wcs.h wcshdr.h \
-                        wcsutil.h
-$(WCSLIB)(wcspih.o)   : cel.h lin.h prj.h spc.h spx.h tab.h wcs.h wcshdr.h \
-                        wcsmath.h
+                        wcserr.h wcsfix.h wcsmath.h wcsunits.h wcsutil.h
+$(WCSLIB)(wcshdr.o)   : cel.h lin.h prj.h spc.h spx.h tab.h wcs.h wcserr.h \
+                        wcshdr.h wcsmath.h wcsutil.h
+$(WCSLIB)(wcspih.o)   : cel.h lin.h prj.h spc.h spx.h tab.h wcs.h wcserr.h \
+                        wcshdr.h wcsmath.h
 $(WCSLIB)(wcsprintf.o): wcsprintf.h
-$(WCSLIB)(wcstrig.o)  : wcsmath.h wcstrig.h
-$(WCSLIB)(wcsulex.o)  : wcsmath.h wcsunits.h
-$(WCSLIB)(wcsunits.o) : wcsunits.h
+$(WCSLIB)(wcstrig.o)  : wcsconfig.h wcsmath.h wcstrig.h
+$(WCSLIB)(wcsulex.o)  : wcserr.h wcsmath.h wcsunits.h
+$(WCSLIB)(wcsunits.o) : wcserr.h wcsunits.h
 $(WCSLIB)(wcsutil.o)  : wcsutil.h
-$(WCSLIB)(wcsutrn.o)  : wcsunits.h
+$(WCSLIB)(wcsutrn.o)  : wcserr.h wcsunits.h
 
-tbth1 tbth1_cfitsio : cel.h wcsconfig.h wcsconfig_tests.h lin.h prj.h spc.h \
-                      spx.h tab.h wcs.h wcsfix.h wcshdr.h
-tcel1   : cel.h prj.h
-tcel2   : cel.h prj.h
-tfitshdr tfitshdr_cfitsio : wcsconfig.h wcsconfig_tests.h fitshdr.h
-tlin    : lin.h
+tbth1 tbth1_cfitsio : cel.h lin.h prj.h spc.h spx.h tab.h wcs.h wcsconfig.h \
+                      wcsconfig_tests.h wcserr.h wcsfix.h wcshdr.h
+tcel1   : cel.h prj.h wcserr.h
+tcel2   : cel.h prj.h wcserr.h
+tfitshdr tfitshdr_cfitsio : fitshdr.h wcsconfig.h wcsconfig_tests.h
+tlin    : lin.h wcserr.h
 tlog    : log.h
-tpih1 tpih1_cfitsio : cel.h wcsconfig.h wcsconfig_tests.h lin.h prj.h spc.h \
-                      spx.h tab.h wcs.h wcsfix.h wcshdr.h wcsprintf.h
-tpih2 tpih2_cfitsio : cel.h wcsconfig.h wcsconfig_tests.h lin.h prj.h spc.h \
-                      spx.h tab.h wcs.h wcshdr.h
-tprj1   : prj.h wcstrig.h
-tprj2   : prj.h
-tspc    : spc.h spx.h wcstrig.h
-tsph    : sph.h wcstrig.h
-tsphdpa : sph.h wcstrig.h
-tspx    : spx.h
-ttab1   : tab.h
-ttab2   : tab.h
-ttab3   : prj.h tab.h
-tunits  : wcsunits.h
-twcs    : cel.h lin.h prj.h spc.h spx.h tab.h wcs.h
-twcsfix : cel.h lin.h prj.h spc.h spx.h tab.h wcs.h wcsfix.h wcsunits.h
-twcshdr : cel.h lin.h prj.h spc.h spx.h tab.h wcs.h wcshdr.h
-twcsmix : cel.h lin.h prj.h spc.h sph.h spx.h tab.h wcs.h
-twcssub : cel.h lin.h prj.h spc.h spx.h tab.h wcs.h
-twcstab : cel.h lin.h prj.h spc.h spx.h tab.h wcs.h wcshdr.h
+tpih1 tpih1_cfitsio : cel.h lin.h prj.h spc.h spx.h tab.h wcs.h wcsconfig.h \
+                      wcsconfig_tests.h wcserr.h wcsfix.h wcshdr.h wcsprintf.h
+tpih2 tpih2_cfitsio : cel.h lin.h prj.h spc.h spx.h tab.h wcs.h wcsconfig.h \
+                      wcsconfig_tests.h wcserr.h wcshdr.h
+tprj1   : prj.h wcsconfig.h wcserr.h wcstrig.h
+tprj2   : prj.h wcserr.h
+tspc    : spc.h spx.h wcsconfig.h wcserr.h wcstrig.h
+tsph    : sph.h wcsconfig.h wcstrig.h
+tsphdpa : sph.h
+tspx    : spx.h wcserr.h
+ttab1   : tab.h wcserr.h
+ttab2   : tab.h wcserr.h
+ttab3   : prj.h tab.h wcserr.h
+tunits  : wcserr.h wcsunits.h
+twcs    : cel.h lin.h log.h prj.h spc.h sph.h spx.h tab.h wcs.h wcsconfig.h \
+          wcsconfig_tests.h wcserr.h wcsfix.h wcshdr.h wcslib.h wcsmath.h \
+          wcsprintf.h wcstrig.h wcsunits.h wcsutil.h
+twcsfix : cel.h lin.h prj.h spc.h spx.h tab.h wcs.h wcserr.h wcsfix.h \
+          wcsunits.h
+twcshdr : cel.h fitshdr.h getwcstab.h lin.h log.h prj.h spc.h sph.h spx.h \
+          tab.h wcs.h wcsconfig.h wcserr.h wcsfix.h wcshdr.h wcslib.h \
+          wcsmath.h wcsprintf.h wcstrig.h wcsunits.h wcsutil.h
+twcsmix : cel.h lin.h prj.h spc.h sph.h spx.h tab.h wcs.h wcserr.h
+twcssub : cel.h lin.h prj.h spc.h spx.h tab.h wcs.h wcserr.h
+twcstab : cel.h fitshdr.h getwcstab.h lin.h log.h prj.h spc.h sph.h spx.h \
+          tab.h wcs.h wcsconfig.h wcserr.h wcsfix.h wcshdr.h wcslib.h \
+          wcsmath.h wcsprintf.h wcstrig.h wcsunits.h wcsutil.h
 
 run_tbth1 run_tbth1_cfitsio : bth.fits
 run_tfitshdr run_tfitshdr_cfitsio : pih.fits
diff --git a/borrow/wcslib/Fortran/GNUmakefile b/borrow/wcslib/Fortran/GNUmakefile
--- a/borrow/wcslib/Fortran/GNUmakefile
+++ b/borrow/wcslib/Fortran/GNUmakefile
@@ -1,5 +1,5 @@
 #-----------------------------------------------------------------------------
-# GNU makefile for building the WCSLIB 4.7 FORTRAN wrappers.
+# GNU makefile for building the WCSLIB 4.13 FORTRAN wrappers.
 #
 # Summary of the main targets
 # ---------------------------
@@ -13,11 +13,15 @@
 #              object library.
 #
 #   check (or test): Compile and run the test programs.  By default they are
-#              executed in batch mode; use
+#              executed in batch mode, and non-graphical tests only report
+#              "PASS" on success.  Use
 #
-#                gmake MODE=interactive check
+#                make MODE=interactive check
 #
-#              to run them interactively.
+#              to run them interactively with full diagnostic output.  To skip
+#              graphical tests even if PGPLOT is available, use
+#
+#                make CHECK=nopgplot check
 #
 #   tests:     Compile the test programs (but don't run them).
 #
@@ -25,7 +29,7 @@
 #   1) If you need to make changes then preferably modify ../makedefs.in
 #      instead and re-run configure.
 #
-#   2) This makefile assumes that the WCSLIB 4.7 sources reside in ../C
+#   2) This makefile assumes that the WCSLIB 4.13 sources reside in ../C
 #      (as in the distribution kit).
 #
 #   3) twcstab assumes that ../C/wcstab.fits has already been generated by
@@ -61,24 +65,34 @@ vpath %.in ..
 
 # For building and exercising the test suite
 # ------------------------------------------
-# Test programs that don't require PGPLOT.
+# Test programs that don't require CFITSIO or PGPLOT.
 TEST_N := tlin tlog tprj1 tsph tspx ttab1 twcs twcssub tpih1 tfitshdr tunits \
           twcsfix
 
-# Test programs that do require PGPLOT.
+# Test programs that require CFITSIO (they don't need PGPLOT).
+TEST_C := twcstab
+
+# Test programs that require PGPLOT but not PGSBOX.
 TEST_P := tspc tprj2 tcel1 ttab2 ttab3 twcsmix
 
+# Test programs that require PGPLOT and PGSBOX.
+TEST_B := tpih2
+
 TESTS  := $(TEST_N)
-ifneq "$(PGPLOTINC)" ""
-ifneq "$(PGPLOTLIB)" ""
-  TESTS   += $(TEST_P) tpih2
+
+# Add test programs that require CFITSIO if we have it.
+ifneq "$(CFITSIOINC)" ""
+ifneq "$(CFITSIOLIB)" ""
+  TESTS  += $(TEST_C)
 endif
 endif
 
-# Test programs that require CFITSIO.
-ifneq "$(CFITSIOINC)" ""
-ifneq "$(CFITSIOLIB)" ""
-TESTS  += twcstab
+# Add test programs that require PGPLOT if we have it.
+ifneq "$(CHECK)" "nopgplot"
+ifneq "$(PGPLOTINC)" ""
+ifneq "$(PGPLOTLIB)" ""
+  TESTS   += $(TEST_P) $(TEST_B)
+endif
 endif
 endif
 
@@ -131,19 +145,68 @@ $(PICLIB)(%.o) : %.f
 run_% : %
 	-@ echo ''
 	-@ $(TIMER)
-	 @ if [ '$(MODE)' = interactive ] ; then \
+	 @ if [ '$(MODE)' = interactive -o '$(VALGRIND)' ] ; then \
 	     printf 'Press <CR> to run $<: ' ; \
 	     read DUMMY ; \
+	   fi ; \
+	   if [ '$(VALGRIND)' ] ; then \
 	     if [ '$<' = tunits ] ; then \
-	       ./$< < ../C/test/units_test ; \
+	       $(VALGRIND) ./$< < test/units_test ; \
 	     else \
-	       ./$< ; \
+	       $(VALGRIND) ./$< ; \
 	     fi ; \
 	   else \
-	     if [ '$<' = tunits ] ; then \
-	       ./$< < ../C/test/units_test ; \
-	     elif [ '$<' != twcshdr ] ; then \
-	       ./$< < /dev/null 2>&1 ; \
+	     if [ '$(filter $<, $(TEST_N) $(TEST_C))' ] ; then \
+	       if [ '$<' = tunits ] ; then \
+	         if [ '$(MODE)' = interactive ] ; then \
+	           ./$< < ../C/test/units_test 2>&1 | tee $<.out ; \
+	         else \
+	           ./$< < ../C/test/units_test > $<.out 2>&1 ; \
+	         fi ; \
+	       else \
+	         if [ '$(MODE)' = interactive ] ; then \
+	           ./$< < /dev/null 2>&1 | tee $<.out ; \
+	         else \
+	           ./$< < /dev/null > $<.out 2>&1 ; \
+	         fi ; \
+	       fi ; \
+	       if grep 'PASS:' $<.out > /dev/null ; then \
+	         if [ '$(MODE)' != interactive ] ; then \
+	           head -2 $<.out ; \
+	           grep 'PASS:' $<.out ; \
+	         fi ; \
+	         echo 'PASS: Fortran/$<' >> test_results ; \
+	       elif [ -f 'test/$<.out' ] ; then \
+	         trap 'rm -f run_test.tmp' 0 1 2 3 15 ; \
+	         sed -e 's/0x[0-9a-f][0-9a-f][0-9a-f]*/0x<address>/g' $<.out > \
+	           run_test.tmp ; \
+	         mv -f run_test.tmp $<.out ; \
+	         if cmp -s $<.out test/$<.out ; then \
+	           if [ '$(MODE)' != interactive ] ; then \
+	             head -2 $<.out ; \
+	             echo 'PASS: Output agrees with Fortran/test/$<.out' ; \
+	           fi ; \
+	           echo 'PASS: Fortran/$<' >> test_results ; \
+	         else \
+	           if [ '$(MODE)' != interactive ] ; then \
+	             cat $<.out ; \
+	           fi ; \
+	           echo '' ; \
+	           echo 'FAIL: Output disagrees with Fortran/test/$<.out' ; \
+	           echo 'FAIL: Fortran/$<' >> test_results ; \
+	         fi ; \
+	       elif [ '$(MODE)' != interactive ] ; then \
+	         cat $<.out ; \
+	         echo 'FAIL: Fortran/$<' >> test_results ; \
+	       fi ; \
+	     elif [ '$(MODE)' = interactive ] ; then \
+	       ./$< ; \
+	     else \
+	       if [ '$<' = tcel2 ] ; then \
+	         echo N | ./$< ; \
+	       else \
+	         ./$< < /dev/null 2>&1 ; \
+	       fi ; \
 	     fi ; \
 	   fi
 	-@ echo ''
@@ -173,7 +236,7 @@ $(SHRLIB) : $(PICLIB)
 	     cd tmp && \
 	     trap 'cd .. ; $(RM) -r tmp' 0 1 2 3 15 ; \
 	     $(AR) x ../$(PICLIB) && \
-	     $(SHRLD) $(LDFLAGS) -o $(@F) *.o && \
+	     $(SHRLD) -o $(@F) *.o $(LDFLAGS) $(LIBS) && \
 	     mv $(@F) ../../C
 
 $(PICLIB) : $(MODULES:%.o=$(PICLIB)(%.o)) ;
@@ -183,12 +246,13 @@ install : build
 	$(INSTALL) -m 444 *.inc $(INCDIR)
 
 clean :
-	-  $(RM) -r *.o *.i a.out core fort.* *.dSYM $(EXTRA_CLEAN)
+	-  $(RM) -r *.o *.i a.out t*.out core fort.* *.dSYM $(EXTRA_CLEAN)
 
 cleaner : clean
+	-  $(RM) .gdb_history
 	-  $(RM) $(TEST_N)
 	-  $(RM) $(TEST_P) tpih2 twcstab
-	-  $(RM) tofits pih.fits
+	-  $(RM) tofits pih.fits test_results
 
 cleanest distclean realclean : cleaner
 	-  $(RM) $(WCSLIB) $(PICLIB) $(SHRLIB)
@@ -199,25 +263,25 @@ tests : $(TESTS)
 
 $(TEST_N) : % : test/%.f $(WCSLIB)
 	-@ echo ''
-	   $(FC) $(FFLAGS) $(LDFLAGS) -o $@ $< $(WCSLIB) $(LIBS)
+	   $(FC) $(FFLAGS) -o $@ $< $(LDFLAGS) $(WCSLIB) $(LIBS)
 	-@ $(RM) $@.o
 
 $(TEST_P) : % : test/%.f $(WCSLIB)
 	-@ echo ''
-	   $(FC) $(FFLAGS) $(LDFLAGS) -o $@ $< $(WCSLIB) $(PGPLOTLIB) $(LIBS)
+	   $(FC) $(FFLAGS) -o $@ $< $(LDFLAGS) $(WCSLIB) $(PGPLOTLIB) $(LIBS)
 	-@ $(RM) $@.o
 
 tpih2 : % : test/%.f $(PGSBOXLIB) $(WCSLIB)
 	-@ echo ''
-	   $(FC) $(FFLAGS) $(LDFLAGS) -o $@ $< $(PGSBOXLIB) $(WCSLIB) \
+	   $(FC) $(FFLAGS) -o $@ $< $(LDFLAGS) $(PGSBOXLIB) $(WCSLIB) \
 	     $(PGPLOTLIB) $(LIBS)
 	-@ $(RM) $@.o
 
 twcstab : test/twcstab.f getwcstab_f.o getwcstab.inc $(FGETWCSTAB) \
     $(WCSLIB)
 	-@ echo ''
-	   $(FC) $(FFLAGS) $(LDFLAGS) -o $@ $< getwcstab_f.o \
-	     $(FGETWCSTAB) $(CFITSIOLIB) $(WCSLIB) $(LIBS)
+	   $(FC) $(FFLAGS) -o $@ $< getwcstab_f.o $(FGETWCSTAB) \
+	     $(LDFLAGS) $(CFITSIOLIB) $(WCSLIB) $(LIBS)
 	-@ $(RM) $@.o
 
 getwcstab_f.o : getwcstab_f.c getwcstab.h
@@ -248,33 +312,33 @@ GNUmakefile : ../makedefs ;
 show ::
 	-@ echo '  MODULES     := $(MODULES)'
 
-# Dependencies
-#-------------
+# Dependencies (use the %.d pattern rule to list them)
+#-----------------------------------------------------
 
-$(WCSLIB)(cel_f.o)      : cel.h wcsconfig.h wcsconfig_f77.h prj.h
-$(WCSLIB)(fitshdr_f.o)  : wcsconfig.h wcsconfig_f77.h fitshdr.h wcsutil.h
-$(WCSLIB)(getwcstab_f.o): wcsconfig.h wcsconfig_f77.h getwcstab.h
-$(WCSLIB)(lin_f.o)      : wcsconfig.h wcsconfig_f77.h lin.h
-$(WCSLIB)(log_f.o)      : wcsconfig.h wcsconfig_f77.h log.h
-$(WCSLIB)(prj_f.o)      : wcsconfig.h wcsconfig_f77.h prj.h
-$(WCSLIB)(spc_f.o)      : wcsconfig.h wcsconfig_f77.h spc.h spx.h wcsutil.h
-$(WCSLIB)(sph_f.o)      : wcsconfig.h wcsconfig_f77.h sph.h
-$(WCSLIB)(spx_f.o)      : wcsconfig.h wcsconfig_f77.h spx.h
-$(WCSLIB)(tab_f.o)      : wcsconfig.h wcsconfig_f77.h tab.h
-$(WCSLIB)(wcs_f.o)      : cel.h wcsconfig.h wcsconfig_f77.h lin.h prj.h \
-                          spc.h spx.h tab.h wcs.h wcsutil.h
-$(WCSLIB)(wcsfix_f.o)   : cel.h wcsconfig.h wcsconfig_f77.h lin.h prj.h \
-                          spc.h spx.h tab.h wcs.h wcsfix.h
-$(WCSLIB)(wcshdr_f.o)   : cel.h wcsconfig.h wcsconfig_f77.h lin.h prj.h \
-                          spc.h spx.h tab.h wcs.h wcshdr.h
-$(WCSLIB)(wcsunits_f.o) : wcsconfig.h wcsconfig_f77.h wcsunits.h wcsutil.h
+$(WCSLIB)(cel_f.o)      : cel.h prj.h wcserr.h wcsconfig_f77.h
+$(WCSLIB)(fitshdr_f.o)  : fitshdr.h wcsconfig.h wcsconfig_f77.h wcsutil.h
+$(WCSLIB)(getwcstab_f.o): getwcstab.h wcsconfig_f77.h
+$(WCSLIB)(lin_f.o)      : lin.h wcsconfig_f77.h wcserr.h
+$(WCSLIB)(log_f.o)      : log.h wcsconfig_f77.h
+$(WCSLIB)(prj_f.o)      : prj.h wcsconfig_f77.h wcserr.h
+$(WCSLIB)(spc_f.o)      : spc.h spx.h wcsconfig_f77.h wcserr.h wcsutil.h
+$(WCSLIB)(sph_f.o)      : sph.h wcsconfig_f77.h
+$(WCSLIB)(spx_f.o)      : spx.h wcsconfig_f77.h wcserr.h
+$(WCSLIB)(tab_f.o)      : tab.h wcsconfig_f77.h wcserr.h
+$(WCSLIB)(wcs_f.o)      : cel.h lin.h prj.h spc.h spx.h tab.h wcs.h \
+                          wcsconfig_f77.h wcserr.h wcsutil.h
+$(WCSLIB)(wcsfix_f.o)   : cel.h lin.h prj.h spc.h spx.h tab.h wcs.h \
+                          wcsconfig_f77.h wcserr.h wcsfix.h
+$(WCSLIB)(wcshdr_f.o)   : cel.h lin.h prj.h spc.h spx.h tab.h wcs.h \
+                          wcsconfig_f77.h wcserr.h wcshdr.h
+$(WCSLIB)(wcsunits_f.o) : wcsconfig_f77.h wcserr.h wcsunits.h wcsutil.h
 
 tcel1   : cel.inc prj.inc
-tfitshdr: fitshdr.inc pih.fits
+tfitshdr: fitshdr.inc wcshdr.inc
 tlin    : lin.inc
 tlog    : log.inc
-tpih1   : wcs.inc wcshdr.inc pih.fits
-tpih2   : wcs.inc wcshdr.inc pih.fits
+tpih1   : wcs.inc wcsfix.inc wcshdr.inc
+tpih2   : wcs.inc wcshdr.inc
 tprj1   : prj.inc
 tprj2   : prj.inc
 tspc    : spc.inc spx.inc
@@ -283,11 +347,11 @@ ttab1   : tab.inc
 ttab2   : tab.inc
 ttab3   : prj.inc tab.inc
 tunits  : wcsunits.inc
-twcs    : cel.inc prj.inc wcs.inc
-twcsfix : wcs.inc
+twcs    : cel.inc prj.inc wcs.inc wcserr.inc wcsmath.inc
+twcsfix : wcs.inc wcsfix.inc wcsunits.inc
 twcsmix : cel.inc lin.inc prj.inc wcs.inc
-twcssub : cel.inc prj.inc wcs.inc
-twcstab : wcs.inc wcshdr.inc
+twcssub : wcs.inc
+twcstab : getwcstab.inc wcs.inc wcsfix.inc wcshdr.inc
 
 run_tfitshdr run_tpih1 run_tpih2: pih.fits
 run_twcstab: ../C/wcstab.fits
